name: Daily Contribution
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # This line is the secret sauce to fix the red X
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Update Log
        run: echo "Manual and Robot Sync: $(date)" > daily_log.txt          
      - name: Commit and Push
        run: |
          git config --local user.email "michetouma@gmail.com"
          git config --local user.name "GitHub Action"
          git add daily_log.txt
          git commit -m "Automated daily check-in" || echo "No changes"
          git push